version: 1
disable_existing_loggers: True
formatters:
    simple:
        format: "%(asctime)s - [%(filename)s][%(funcName)s] - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ./log/mpsiemsdk.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

loggers:
    Common:
        level: INFO
        handlers: [ console, file_handler ]
        propagate: no
    MPSIEMAuth:
        level: INFO
        handlers: [console, file_handler]
        propagate: no
    # здесь можно добавить логирование для каждого модуля отдельно, указав его имя класса.
root:
    level: INFO
    handlers: [console, file_handler]